title: Jessica Paoli, design babe
email: meow@jessicapaoli.com
author: Jessica Paoli
description: I’m an interdisciplinary designer, developer, and illustrator (Design Babe) dual-wielding compassion + cuteness in the Midwest.
baseurl:  "" # the subpath of your site, e.g. /blog
url:      "http://localhost:3000" # the base hostname & protocol for your site

locale:       en-US
lang:         en-US
encoding:     "utf-8"


# Build setings
markdown:     kramdown
highlighter:  rouge
permalink:    /:year/:title
future:       false

whitelist:    []
plugins:      []


# Exclude from site build
exclude:
  - .DS_Store
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md


# Collections
collections:
  sketches:
    output: true
    permalink: /sketchbook/:path/
  projects:
    output: true
    permalink: /project/:path/
  products:
    output: true
    permalink: /shop/:path/

# Custom variables
mediapath:
  post: media/posts/
